name: analytics
on:
  push:
    branches:
      - master

jobs:
  analyze:
    name: Code Metrics Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install radon lizard pylint mccabe xenon pycodestyle cognitive-complexity cloc scc

      - name: Analyze with Radon
        run: |
          mkdir -p metrics
          echo "=== Cyclomatic Complexity ===" > metrics_report.txt
          find . -type f -name "*.py" | xargs --no-run-if-empty radon cc --show-complexity --average >> metrics_report.txt || true

          echo -e "\n=== Maintainability Index ===" >> metrics_report.txt
          find . -type f -name "*.py" | xargs --no-run-if-empty radon mi --show >> metrics_report.txt || true

          echo -e "\n=== Raw Metrics ===" >> metrics_report.txt
          find . -type f -name "*.py" | xargs --no-run-if-empty radon raw --summary >> metrics_report.txt || true

          echo -e "\n=== Halstead Metrics ===" >> metrics_report.txt
          find . -type f -name "*.py" | xargs --no-run-if-empty radon hal >> metrics_report.txt || true

      - name: Generate detailed reports
        run: |
          mkdir -p metrics
          # JSON reports
          find . -type f -name "*.py" | xargs --no-run-if-empty radon cc --json > metrics/complexity.json || true
          find . -type f -name "*.py" | xargs --no-run-if-empty radon raw --json > metrics/raw_metrics.json || true
          find . -type f -name "*.py" | xargs --no-run-if-empty radon hal --json > metrics/halstead.json || true
          lizard . --xml > metrics/lizard_report.xml || true
          cp metrics_report.txt metrics/full_report.txt
